# Configuración de memoria por defecto para comandos gradle. Puede ser sobrescrito por usuario o propiedades de línea de comandos.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Propiedades del Entorno
# Puedes encontrar las últimas versiones aquí: https://projects.neoforged.net/neoforged/neoforge
# La versión de Minecraft debe coincidir con la versión de Neo para obtener un artefacto válido
minecraft_version=1.21.1
# El rango de versión de Minecraft puede usar cualquier versión de lanzamiento de Minecraft como límites.
minecraft_version_range=[1.21.1,1.22)
# La versión de Neo debe coincidir con la versión de Minecraft para obtener un artefacto válido
neo_version=21.1.186
# El rango de versión de Neo puede usar cualquier versión de Neo como límites
neo_version_range=[21,)
# El rango de versión del cargador solo puede usar la versión principal de FML como límites
loader_version_range=[4,)

parchment_minecraft_version=1.21.6
parchment_mappings_version=2025.06.29

## Propiedades del Mod

# El identificador único del mod. Debe estar en minúsculas en idioma inglés. Debe coincidir con la expresión regular [a-z][a-z0-9_]{1,63}
# Debe coincidir con la constante String ubicada en la clase principal del mod anotada con @Mod.
mod_id=tempbansm
# El nombre de visualización legible para humanos del mod.
mod_name=TempbanSM
# La licencia del mod. Revisa tus opciones en https://choosealicense.com/. Todos los Derechos Reservados es el valor por defecto.
mod_license=MIT
# La versión del mod. Ver https://semver.org/
mod_version=1.0.0
# El ID de grupo para el mod. Solo es importante cuando se publica como artefacto en un repositorio Maven.
# Esto debe coincidir con el paquete base usado para las fuentes del mod.
# Ver https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=karrito.mods
# Los autores del mod. Esta es una cadena de texto simple que se usa para propósitos de visualización en la lista de mods.
mod_authors=AnsfernyVilcarima
# La descripción del mod. Esta es una cadena de texto multilínea simple que se usa para propósitos de visualización en la lista de mods.
mod_description=Mod para servidores que agrega comandos de baneo temporal con duración específica y mensajes personalizados en español.