modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="tempbansm"
version="${mod_version}"
displayName="TempbanSM"
description="Un mod que agrega comandos de baneo temporal con mensajes personalizados."
authors="AnsfernyVilcarima"

[[dependencies.tempbansm]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.tempbansm]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"